/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { ContinentContentModelContentType } from './continentContentModelContentType';
import type { ContinentPropertiesModel } from './continentPropertiesModel';
import type { IApiContentModelBase } from './iApiContentModelBase';

export type ContinentContentModel = Omit<IApiContentModelBase, 'contentType'> & {
  properties?: ContinentPropertiesModel;
  contentType: ContinentContentModelContentType;
};
