/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { CountryContentModelContentType } from './countryContentModelContentType';
import type { CountryPropertiesModel } from './countryPropertiesModel';
import type { IApiContentModelBase } from './iApiContentModelBase';

export type CountryContentModel = Omit<IApiContentModelBase, 'contentType'> & {
  properties?: CountryPropertiesModel;
  contentType: CountryContentModelContentType;
};
