/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { ContinentContentModel } from './continentContentModel';
import type { CountryContentModel } from './countryContentModel';
import type { HomePageContentModel } from './homePageContentModel';
import type { SettingsContentModel } from './settingsContentModel';
import type { YearContentModel } from './yearContentModel';

export type IApiContentModel = HomePageContentModel | CountryContentModel | ContinentContentModel | YearContentModel | SettingsContentModel;
