/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { ApiContentRouteModel } from './apiContentRouteModel';
import type { IApiElementModelBase } from './iApiElementModelBase';

export type IApiContentModelBase = Omit<IApiElementModelBase, 'contentType'> & ({
  readonly id: string;
  readonly contentType: string;
  /** @nullable */
  readonly name?: string | null;
  readonly createDate: string;
  readonly updateDate: string;
  readonly route: ApiContentRouteModel;
});
