/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiContentResponseModelBase } from './iApiContentResponseModelBase';
import type { YearContentModel } from './yearContentModel';
import type { YearContentResponseModelContentType } from './yearContentResponseModelContentType';

export type YearContentResponseModel = Omit<IApiContentResponseModelBase & YearContentModel, 'contentType'> & {
  contentType: YearContentResponseModelContentType;
};
